name: UltimateChat
main: br.net.fabiozumbi12.UltimateChat.Bukkit.UChat
version: ${project.version}
author: FabioZumbi12
description: ${project.description}
softdepend: [mcMMO, SkillAPI, Essentials, SimpleClans, Vault, MarriageMaster, Marriage, PlaceholderAPI, Factions, JDALibLoaderBukkit]
api-version: 1.13
commands:
  uchat:
    description: "Main command for ${project.name}."
    aliases: [uchat, chat]
  channel:
    description: "Channel commands"
  tell:
    description: "Tell command"
  ubroadcast:
    description: "Broadcast command"
  umsg:
    description: "Send a message to player"
permissions:
  uchat.admin:
    description: "All admin commands."
    default: op
    children:
      uchat.cmd.reload: true
      uchat.cmd.spy: true
      uchat.chat-spy.all: true
      uchat.cmd.mute: true
      uchat.cmd.tempmute: true
      uchat.cmd.umsg: true
      uchat.chat.mention: true
      uchat.chat.color: true
      uchat.chat.color.formats: true
      uchat.chat.color.magic: true
      uchat.cmd.clear-all: true
      uchat.channel.admin.read: true
      uchat.channel.admin.write: true
      uchat.cant-ignore.admin: true
      uchat.broadcast: true      
      uchat.bypass-protections: true
      uchat.discord.mention: true
  uchat.player:
    description: "All player commands."
    default: true
    children:
      uchat.cmd.ignore.player: true
      uchat.cmd.ignore.channel: true
      uchat.cant-ignore.local: true
      uchat.cmd.tell: true
      uchat.cmd.msgtoggle: true
      uchat.cmd.clear: true
      uchat.chat.click-urls: true
      uchat.channel.global.read: true
      uchat.channel.global.write: true
      uchat.channel.local.read: true
      uchat.channel.local.write: true
      uchat.password: true
  uchat.bypass-protections:
    description: "Permissions to bypass chat checks."
    default: false
    children:
      uchat.bypass-spam: true
      uchat.bypass-censor: true
      uchat.bypass-anti-ip: true
      uchat.bypass-enhancement: true